### ISSUE TITLE
Question about Direct3D11CaptureFramePool latency

### ISSUE THREAD

**Issue by WHalcyon** [lovettchris/wincam#7]
First of all thank you for creating this project, it's an invaluable resource as there's very little information on Direct3D11CaptureFramePool online.

I'm looking for a method on Windows to capture the screen with minimal latency. In my ideal design, each frame is transferred into a buffer or queue as soon as it's rendered. My python application awaits the queue to be non-empty and processes the image as soon as it is enqueued.

My goal is to capture the image within 1ms within the frame being rendered. My capture size is only 480x480 so the numpy operations should be efficient. I'm currently using GDI and it's fast but my concern is that I am retrieving stale frames, several milliseconds from the time the frame is captured to the moment it is retrieved.

Is Direct3D11CaptureFramePool and wincam the best solution to my problem?

**Comment by lovettchris** [comment]
Hi, sounds like you have similar requirements to me, and is the whole reason I created wincam, namely, low latency screen capture for python.  Getting down to 1ms is challenging though unless you can find a monitor that has a refresh rate of 1000.  I can get 120fps on a 120fps monitor though.  The Direct3D11CaptureFramePool is rate limited on your monitor refresh rate. So if wincam ran any faster than that you would not see the intervening updates anyway since they were never blitted to the screen.  So if you really do have an app that wants to update that fast then you will need to figure out a different solution (get the app to write to a shared buffer or something...

**Comment by WHalcyon** [comment]
Sorry I should've been a bit clearer, I just need the capture event handler to retrieve, crop, and output the image in around 1ms of the frame being rendered. On a 120fps display this will give me 7ms to process and do operations on the data before the next frame arrives (which I'll probably need).

It sounds like wincam is a good fit for my use case, thank you very much.

**Comment by lovettchris** [comment]
Ah, I see then yes the overhead should be low, I have not measured it precisely, but you will see that  the C++ class SimpleCapture::ReadNextFrame has a semaphore wait on the next frame, which is cleared when DirectX calls SimpleCapture::OnFrameArrived.  This ensures it never returns a null or duplicate frame, it always returns one and only one new frame each time you call get_rgb_frame.  So to get minimal overhead you will need to throttle your calls to no more than the monitor refresh rate, then you should see very low latency once you get on the right cadence.  You will also get higher throughput if there's no "resizing" going on, in fact you might be able to remove the np.resize call on line 63 of dxcam.py, but you can't avoid the np.frombuffer copy.  We could add numpy C++ awareness to the C++ code and we might be able to avoid the double copy that way (copy from directX into buffer, then from buffer into numpy).

**Comment by karwan5880** [comment]
I did an analysis on window of size 1366*768. 

most of the time spent is on:
hr = m_d3dContext->Map(copiedImage.get(), subresource, D3D11_MAP_READ, 0, &resource);
~0.0006368 sec. 
np.frombuffer() operation took:
~0.0000135 sec. (negligible?)
np.reshape() took:
~0.0000186 sec. (negligible?) 
memcpy() took:
~0.0003621 sec. 

so, combining ->Map() operation + memcpy() operation, each ReadPixels call will costs ~0.001 second. 

before i found this repo, i was doing my own study on windows graphics capture, then i start comparing my code with yours, i was able to make my codes work, but then, after i study your code, i found that there is one difference, i did not use memcpy to copy the .pData to ptr, instead, i store .pData to a pointer, and then assign ptr to the pointer: 

tmpsrc = resource.pData; // tmpsrc is a class member, void* tmpsrc = nullptr;
*buffer = tmpsrc; // *buffer is an argument of type void** buffer

and so, in the python:
self._buffer= ctypes.POINTER(ctypes.c_ubyte)()
self.lib.ReadNextFrame(ctypes.byref(self._buffer), len(self._buffer))

then, instead of doing self._buffer = ct.create_string_buffer(self._size), i create dynamic memory in the .dll, 
int totalbytes = height * rowpitch;
*buffer= new BYTE[totalbytes];

and then finally, construct the np image:

buffer_shape_1D = (self.totalbytes.value,)
np_array_1D = np.ctypeslib.as_array(self.data_ptr, shape=buffer_shape_1D)
image_shape_3D = (self.height.value, self.rowpitch.value // 4, 4) # (height, width, channels)
image = np_array_1D.reshape(image_shape_3D) # up until this point i still get black pixel at the right end, maybe further reshape/cut the width, 

i am not sure all the logic/magic behind this, but this works on my end, and i can omit the operation of memcpy by just assigning to void* tmpsrc, 
i am also not very sure if my code has any memory leak issue at all, because i am not as experienced nor good in c++.

**Comment by lovettchris** [comment]
Interesting idea, thanks.
